steps:
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args: ['startup.sh']
  secretEnv: ['GITHUB_TOKEN']
- name: goreleaser/goreleaser
  script: |
    #!/usr/bin/env bash
    goreleaser release --clean --verbose
  secretEnv: ['GITHUB_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/tomburke-gcf-source-repo/secrets/GITHUB_TOKEN/versions/1
    env: 'GITHUB_TOKEN'
options:
  logging: CLOUD_LOGGING_ONLY