steps:
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args: ['startup.sh']
  secretEnv: ['GITHUB_TOKEN']
- name: goreleaser/goreleaser
  script: |
    #!/usr/bin/env bash
    source /tmp/release_env
    goreleaser release --clean --verbose
availableSecrets:
  secretManager:
  - versionName: projects/tomburke-gcf-source-repo/secrets/GITHUB_TOKEN/versions/2
    env: 'GITHUB_TOKEN'
options:
  logging: CLOUD_LOGGING_ONLY