steps:
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args: ['startup.sh']
  secretEnv: ['GITHUB_TOKEN']
- name: goreleaser/goreleaser:latest
  script: |
    #!/usr/bin/env bash
    source /github_assets/release_env
    exec env goreleaser release --clean --verbose
  secretEnv: ['GITHUB_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/tomburke-gcf-source-repo/secrets/GITHUB_TOKEN/versions/2
    env: 'GITHUB_TOKEN'
options:
  logging: CLOUD_LOGGING_ONLY
  volumes:
  - name: 'github-assets'
    path: '/github_assets'